/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rgbdslam_OpenCV */

#ifndef _Included_rgbdslam_OpenCV
#define _Included_rgbdslam_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rgbdslam_OpenCV
 * Method:    cvExtractFeatures
 * Signature: ([IIIDDI[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_rgbdslam_OpenCV_cvExtractFeatures
  (JNIEnv *, jobject, jintArray, jint, jint, jdouble, jdouble, jint, jintArray, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
