/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class april_vis_GL */

#ifndef _Included_april_vis_GL
#define _Included_april_vis_GL
#ifdef __cplusplus
extern "C" {
#endif
#undef april_vis_GL_VBO_TYPE_VERTEX
#define april_vis_GL_VBO_TYPE_VERTEX 1L
#undef april_vis_GL_VBO_TYPE_NORMAL
#define april_vis_GL_VBO_TYPE_NORMAL 2L
#undef april_vis_GL_VBO_TYPE_COLOR
#define april_vis_GL_VBO_TYPE_COLOR 3L
#undef april_vis_GL_VBO_TYPE_TEX_COORD
#define april_vis_GL_VBO_TYPE_TEX_COORD 4L
#undef april_vis_GL_VBO_TYPE_ELEMENT_ARRAY
#define april_vis_GL_VBO_TYPE_ELEMENT_ARRAY 5L
#undef april_vis_GL_OP_TRANSLATED
#define april_vis_GL_OP_TRANSLATED 1L
#undef april_vis_GL_OP_PUSHMATRIX
#define april_vis_GL_OP_PUSHMATRIX 2L
#undef april_vis_GL_OP_POPMATRIX
#define april_vis_GL_OP_POPMATRIX 3L
#undef april_vis_GL_OP_MULTMATRIXD
#define april_vis_GL_OP_MULTMATRIXD 4L
#undef april_vis_GL_OP_LOADIDENTITY
#define april_vis_GL_OP_LOADIDENTITY 5L
#undef april_vis_GL_OP_MATRIXMODE
#define april_vis_GL_OP_MATRIXMODE 6L
#undef april_vis_GL_OP_ENABLE
#define april_vis_GL_OP_ENABLE 7L
#undef april_vis_GL_OP_DISABLE
#define april_vis_GL_OP_DISABLE 8L
#undef april_vis_GL_OP_SCALED
#define april_vis_GL_OP_SCALED 9L
#undef april_vis_GL_OP_CLEAR
#define april_vis_GL_OP_CLEAR 10L
#undef april_vis_GL_OP_COLOR
#define april_vis_GL_OP_COLOR 11L
#undef april_vis_GL_OP_CLEARCOLOR
#define april_vis_GL_OP_CLEARCOLOR 12L
#undef april_vis_GL_OP_CLEARDEPTH
#define april_vis_GL_OP_CLEARDEPTH 13L
#undef april_vis_GL_OP_SCISSOR
#define april_vis_GL_OP_SCISSOR 14L
#undef april_vis_GL_OP_LIGHTFV
#define april_vis_GL_OP_LIGHTFV 15L
#undef april_vis_GL_OP_LIGHTMODELI
#define april_vis_GL_OP_LIGHTMODELI 16L
#undef april_vis_GL_OP_COLORMATERIAL
#define april_vis_GL_OP_COLORMATERIAL 17L
#undef april_vis_GL_OP_MATERIALF
#define april_vis_GL_OP_MATERIALF 18L
#undef april_vis_GL_OP_MATERIALFV
#define april_vis_GL_OP_MATERIALFV 19L
#undef april_vis_GL_OP_DEPTHFUNC
#define april_vis_GL_OP_DEPTHFUNC 20L
#undef april_vis_GL_OP_BLENDFUNC
#define april_vis_GL_OP_BLENDFUNC 21L
#undef april_vis_GL_OP_POLYGONMODE
#define april_vis_GL_OP_POLYGONMODE 22L
#undef april_vis_GL_OP_HINT
#define april_vis_GL_OP_HINT 23L
#undef april_vis_GL_OP_SHADEMODEL
#define april_vis_GL_OP_SHADEMODEL 24L
#undef april_vis_GL_OP_BEGIN
#define april_vis_GL_OP_BEGIN 25L
#undef april_vis_GL_OP_END
#define april_vis_GL_OP_END 26L
#undef april_vis_GL_OP_VERTEX2D
#define april_vis_GL_OP_VERTEX2D 27L
#undef april_vis_GL_OP_VERTEX3D
#define april_vis_GL_OP_VERTEX3D 28L
#undef april_vis_GL_OP_VIEWPORT
#define april_vis_GL_OP_VIEWPORT 29L
#undef april_vis_GL_OP_DRAWARRAYS
#define april_vis_GL_OP_DRAWARRAYS 30L
#undef april_vis_GL_OP_POLYGONOFFSET
#define april_vis_GL_OP_POLYGONOFFSET 31L
#undef april_vis_GL_OP_LINEWIDTH
#define april_vis_GL_OP_LINEWIDTH 32L
#undef april_vis_GL_OP_PUSHATTRIB
#define april_vis_GL_OP_PUSHATTRIB 33L
#undef april_vis_GL_OP_POPATTRIB
#define april_vis_GL_OP_POPATTRIB 34L
#undef april_vis_GL_OP_POINTSIZE
#define april_vis_GL_OP_POINTSIZE 35L
#undef april_vis_GL_OP_TEXCOORD2D
#define april_vis_GL_OP_TEXCOORD2D 36L
#undef april_vis_GL_OP_NORMAL3F
#define april_vis_GL_OP_NORMAL3F 37L
#undef april_vis_GL_OP_ALPHA_FUNC
#define april_vis_GL_OP_ALPHA_FUNC 38L
#undef april_vis_GL_OP_ROTATED
#define april_vis_GL_OP_ROTATED 39L
#undef april_vis_GL_OP_DRAWRANGEELEMENTS
#define april_vis_GL_OP_DRAWRANGEELEMENTS 40L
#undef april_vis_GL_GL_TRUE
#define april_vis_GL_GL_TRUE 1L
#undef april_vis_GL_GL_FALSE
#define april_vis_GL_GL_FALSE 0L
#undef april_vis_GL_GL_MODELVIEW
#define april_vis_GL_GL_MODELVIEW 5888L
#undef april_vis_GL_GL_PROJECTION
#define april_vis_GL_GL_PROJECTION 5889L
#undef april_vis_GL_GL_TEXTURE
#define april_vis_GL_GL_TEXTURE 5890L
#undef april_vis_GL_GL_COLOR_BUFFER_BIT
#define april_vis_GL_GL_COLOR_BUFFER_BIT 16384L
#undef april_vis_GL_GL_DEPTH_BUFFER_BIT
#define april_vis_GL_GL_DEPTH_BUFFER_BIT 256L
#undef april_vis_GL_GL_STENCIL_BUFFER_BIT
#define april_vis_GL_GL_STENCIL_BUFFER_BIT 64L
#undef april_vis_GL_GL_LIGHTING
#define april_vis_GL_GL_LIGHTING 2896L
#undef april_vis_GL_GL_LIGHT0
#define april_vis_GL_GL_LIGHT0 16384L
#undef april_vis_GL_GL_LIGHT1
#define april_vis_GL_GL_LIGHT1 16385L
#undef april_vis_GL_GL_LIGHT2
#define april_vis_GL_GL_LIGHT2 16386L
#undef april_vis_GL_GL_SPOT_EXPONENT
#define april_vis_GL_GL_SPOT_EXPONENT 4613L
#undef april_vis_GL_GL_SPOT_CUTOFF
#define april_vis_GL_GL_SPOT_CUTOFF 4614L
#undef april_vis_GL_GL_CONSTANT_ATTENUATION
#define april_vis_GL_GL_CONSTANT_ATTENUATION 4615L
#undef april_vis_GL_GL_LINEAR_ATTENUATION
#define april_vis_GL_GL_LINEAR_ATTENUATION 4616L
#undef april_vis_GL_GL_QUADRATIC_ATTENUATION
#define april_vis_GL_GL_QUADRATIC_ATTENUATION 4617L
#undef april_vis_GL_GL_AMBIENT
#define april_vis_GL_GL_AMBIENT 4608L
#undef april_vis_GL_GL_DIFFUSE
#define april_vis_GL_GL_DIFFUSE 4609L
#undef april_vis_GL_GL_SPECULAR
#define april_vis_GL_GL_SPECULAR 4610L
#undef april_vis_GL_GL_SHININESS
#define april_vis_GL_GL_SHININESS 5633L
#undef april_vis_GL_GL_EMISSION
#define april_vis_GL_GL_EMISSION 5632L
#undef april_vis_GL_GL_POSITION
#define april_vis_GL_GL_POSITION 4611L
#undef april_vis_GL_GL_SPOT_DIRECTION
#define april_vis_GL_GL_SPOT_DIRECTION 4612L
#undef april_vis_GL_GL_AMBIENT_AND_DIFFUSE
#define april_vis_GL_GL_AMBIENT_AND_DIFFUSE 5634L
#undef april_vis_GL_GL_COLOR_INDEXES
#define april_vis_GL_GL_COLOR_INDEXES 5635L
#undef april_vis_GL_GL_LIGHT_MODEL_TWO_SIDE
#define april_vis_GL_GL_LIGHT_MODEL_TWO_SIDE 2898L
#undef april_vis_GL_GL_LIGHT_MODEL_LOCAL_VIEWER
#define april_vis_GL_GL_LIGHT_MODEL_LOCAL_VIEWER 2897L
#undef april_vis_GL_GL_LIGHT_MODEL_AMBIENT
#define april_vis_GL_GL_LIGHT_MODEL_AMBIENT 2899L
#undef april_vis_GL_GL_FRONT_AND_BACK
#define april_vis_GL_GL_FRONT_AND_BACK 1032L
#undef april_vis_GL_GL_SHADE_MODEL
#define april_vis_GL_GL_SHADE_MODEL 2900L
#undef april_vis_GL_GL_FLAT
#define april_vis_GL_GL_FLAT 7424L
#undef april_vis_GL_GL_SMOOTH
#define april_vis_GL_GL_SMOOTH 7425L
#undef april_vis_GL_GL_COLOR_MATERIAL
#define april_vis_GL_GL_COLOR_MATERIAL 2903L
#undef april_vis_GL_GL_COLOR_MATERIAL_FACE
#define april_vis_GL_GL_COLOR_MATERIAL_FACE 2901L
#undef april_vis_GL_GL_COLOR_MATERIAL_PARAMETER
#define april_vis_GL_GL_COLOR_MATERIAL_PARAMETER 2902L
#undef april_vis_GL_GL_NORMALIZE
#define april_vis_GL_GL_NORMALIZE 2977L
#undef april_vis_GL_GL_DEPTH_TEST
#define april_vis_GL_GL_DEPTH_TEST 2929L
#undef april_vis_GL_GL_LEQUAL
#define april_vis_GL_GL_LEQUAL 515L
#undef april_vis_GL_GL_ENABLE_BIT
#define april_vis_GL_GL_ENABLE_BIT 8192L
#undef april_vis_GL_GL_SCISSOR_TEST
#define april_vis_GL_GL_SCISSOR_TEST 3089L
#undef april_vis_GL_GL_BLEND
#define april_vis_GL_GL_BLEND 3042L
#undef april_vis_GL_GL_SRC_ALPHA
#define april_vis_GL_GL_SRC_ALPHA 770L
#undef april_vis_GL_GL_ONE_MINUS_SRC_ALPHA
#define april_vis_GL_GL_ONE_MINUS_SRC_ALPHA 771L
#undef april_vis_GL_GL_ZERO
#define april_vis_GL_GL_ZERO 0L
#undef april_vis_GL_GL_ONE
#define april_vis_GL_GL_ONE 1L
#undef april_vis_GL_GL_FILL
#define april_vis_GL_GL_FILL 6914L
#undef april_vis_GL_GL_FRONT
#define april_vis_GL_GL_FRONT 1028L
#undef april_vis_GL_GL_BACK
#define april_vis_GL_GL_BACK 1029L
#undef april_vis_GL_GL_POLYGON_OFFSET_FILL
#define april_vis_GL_GL_POLYGON_OFFSET_FILL 32823L
#undef april_vis_GL_GL_POLYGON_OFFSET_LINE
#define april_vis_GL_GL_POLYGON_OFFSET_LINE 10754L
#undef april_vis_GL_GL_POINT_SMOOTH
#define april_vis_GL_GL_POINT_SMOOTH 2832L
#undef april_vis_GL_GL_PERSPECTIVE_CORRECTION_HINT
#define april_vis_GL_GL_PERSPECTIVE_CORRECTION_HINT 3152L
#undef april_vis_GL_GL_POINT_SMOOTH_HINT
#define april_vis_GL_GL_POINT_SMOOTH_HINT 3153L
#undef april_vis_GL_GL_LINE_SMOOTH_HINT
#define april_vis_GL_GL_LINE_SMOOTH_HINT 3154L
#undef april_vis_GL_GL_POLYGON_SMOOTH_HINT
#define april_vis_GL_GL_POLYGON_SMOOTH_HINT 3155L
#undef april_vis_GL_GL_FOG_HINT
#define april_vis_GL_GL_FOG_HINT 3156L
#undef april_vis_GL_GL_POLYGON_SMOOTH
#define april_vis_GL_GL_POLYGON_SMOOTH 2881L
#undef april_vis_GL_GL_DONT_CARE
#define april_vis_GL_GL_DONT_CARE 4352L
#undef april_vis_GL_GL_FASTEST
#define april_vis_GL_GL_FASTEST 4353L
#undef april_vis_GL_GL_NICEST
#define april_vis_GL_GL_NICEST 4354L
#undef april_vis_GL_GL_LINE_SMOOTH
#define april_vis_GL_GL_LINE_SMOOTH 2848L
#undef april_vis_GL_GL_LINE_STIPPLE
#define april_vis_GL_GL_LINE_STIPPLE 2852L
#undef april_vis_GL_GL_CULL_FACE
#define april_vis_GL_GL_CULL_FACE 2884L
#undef april_vis_GL_GL_CULL_FACE_MODE
#define april_vis_GL_GL_CULL_FACE_MODE 2885L
#undef april_vis_GL_GL_POINTS
#define april_vis_GL_GL_POINTS 0L
#undef april_vis_GL_GL_LINES
#define april_vis_GL_GL_LINES 1L
#undef april_vis_GL_GL_LINE_LOOP
#define april_vis_GL_GL_LINE_LOOP 2L
#undef april_vis_GL_GL_LINE_STRIP
#define april_vis_GL_GL_LINE_STRIP 3L
#undef april_vis_GL_GL_TRIANGLES
#define april_vis_GL_GL_TRIANGLES 4L
#undef april_vis_GL_GL_TRIANGLE_STRIP
#define april_vis_GL_GL_TRIANGLE_STRIP 5L
#undef april_vis_GL_GL_TRIANGLE_FAN
#define april_vis_GL_GL_TRIANGLE_FAN 6L
#undef april_vis_GL_GL_QUADS
#define april_vis_GL_GL_QUADS 7L
#undef april_vis_GL_GL_QUAD_STRIP
#define april_vis_GL_GL_QUAD_STRIP 8L
#undef april_vis_GL_GL_POLYGON
#define april_vis_GL_GL_POLYGON 9L
#undef april_vis_GL_GL_RGBA8
#define april_vis_GL_GL_RGBA8 32856L
#undef april_vis_GL_GL_ALPHA8
#define april_vis_GL_GL_ALPHA8 32828L
#undef april_vis_GL_GL_LUMINANCE8
#define april_vis_GL_GL_LUMINANCE8 32832L
#undef april_vis_GL_GL_BGRA
#define april_vis_GL_GL_BGRA 32993L
#undef april_vis_GL_GL_UNSIGNED_INT_8_8_8_8_REV
#define april_vis_GL_GL_UNSIGNED_INT_8_8_8_8_REV 33639L
#undef april_vis_GL_GL_ABGR_EXT
#define april_vis_GL_GL_ABGR_EXT 32768L
#undef april_vis_GL_GL_RGB8
#define april_vis_GL_GL_RGB8 32849L
#undef april_vis_GL_GL_LUMINANCE
#define april_vis_GL_GL_LUMINANCE 6409L
#undef april_vis_GL_GL_ALPHA
#define april_vis_GL_GL_ALPHA 6406L
#undef april_vis_GL_GL_UNSIGNED_BYTE
#define april_vis_GL_GL_UNSIGNED_BYTE 5121L
#undef april_vis_GL_GL_ALPHA_TEST
#define april_vis_GL_GL_ALPHA_TEST 3008L
#undef april_vis_GL_GL_GREATER
#define april_vis_GL_GL_GREATER 516L
#undef april_vis_GL_GL_GEQUAL
#define april_vis_GL_GL_GEQUAL 518L
#undef april_vis_GL_GL_ALWAYS
#define april_vis_GL_GL_ALWAYS 519L
/*
 * Class:     april_vis_GL
 * Method:    gl_initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1initialize
  (JNIEnv *, jclass);

/*
 * Class:     april_vis_GL
 * Method:    gl_fbo_create
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1fbo_1create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_vis_GL
 * Method:    gl_fbo_destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1fbo_1destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_vis_GL
 * Method:    gl_fbo_bind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1fbo_1bind
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_vis_GL
 * Method:    gl_read_pixels
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_april_vis_GL_gl_1read_1pixels
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_vis_GL
 * Method:    gl_read_pixels2
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1read_1pixels2__II_3I
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     april_vis_GL
 * Method:    gl_read_pixels2
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1read_1pixels2__II_3B
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     april_vis_GL
 * Method:    gl_ops
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1ops
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     april_vis_GL
 * Method:    gldata_bind
 * Signature: (IJII[F)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1bind__IJII_3F
  (JNIEnv *, jclass, jint, jlong, jint, jint, jfloatArray);

/*
 * Class:     april_vis_GL
 * Method:    gldata_bind
 * Signature: (IJII[D)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1bind__IJII_3D
  (JNIEnv *, jclass, jint, jlong, jint, jint, jdoubleArray);

/*
 * Class:     april_vis_GL
 * Method:    gldata_bind
 * Signature: (IJII[I)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1bind__IJII_3I
  (JNIEnv *, jclass, jint, jlong, jint, jint, jintArray);

/*
 * Class:     april_vis_GL
 * Method:    gldata_bind
 * Signature: (IJII[S)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1bind__IJII_3S
  (JNIEnv *, jclass, jint, jlong, jint, jint, jshortArray);

/*
 * Class:     april_vis_GL
 * Method:    gldata_unbind
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1unbind
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     april_vis_GL
 * Method:    gldata_tex_bind
 * Signature: (JIIIII[I)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1tex_1bind__JIIIII_3I
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     april_vis_GL
 * Method:    gldata_tex_bind
 * Signature: (JIIIII[B)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1tex_1bind__JIIIII_3B
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     april_vis_GL
 * Method:    gldata_tex_unbind
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1tex_1unbind
  (JNIEnv *, jclass, jlong);

/*
 * Class:     april_vis_GL
 * Method:    gldata_begin_frame
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1begin_1frame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     april_vis_GL
 * Method:    gldata_end_frame_and_collect
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gldata_1end_1frame_1and_1collect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     april_vis_GL
 * Method:    gl_get_error
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_april_vis_GL_gl_1get_1error
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
